2017-03-16 09:26:59,587 [INFO] from application in ForkJoinPool-1-worker-1 - Creating Pool for datasource 'default'
2017-03-16 09:26:59,988 [INFO] from play.api.db.HikariCPConnectionPool in ForkJoinPool-1-worker-1 - datasource [default] bound to JNDI as DefaultDS
2017-03-16 09:27:00,006 [INFO] from play.api.db.DefaultDBApi in ForkJoinPool-1-worker-1 - Database [default] connected at jdbc:mysql://localhost/mavericks_project
2017-03-16 09:27:02,529 [ERROR] from application in ForkJoinPool-1-worker-1 - Failed to create image upload directory
2017-03-16 09:27:02,795 [INFO] from play.api.Play in ForkJoinPool-1-worker-1 - Application started (Dev)
2017-03-16 09:27:03,683 [DEBUG] from application in application-akka.actor.default-dispatcher-7 - d1ef521d1a75eb1180aea02396958d6cee6bf82f9f885ca96e5d0a865a98d842
2017-03-16 09:27:03,730 [DEBUG] from application in application-akka.actor.default-dispatcher-7 - be8f418957e827e427a9d1ef521d1a75eb1180aea02396958d6cee6bf82f9f885ca96e5d0a865a98d842sakondi
2017-03-16 09:28:06,827 [INFO] from application in application-akka.actor.default-dispatcher-6 - Shutting down connection pool.
2017-03-16 09:28:06,954 [INFO] from application in application-akka.actor.default-dispatcher-6 - Creating Pool for datasource 'default'
2017-03-16 09:28:06,958 [INFO] from play.api.db.HikariCPConnectionPool in application-akka.actor.default-dispatcher-6 - datasource [default] bound to JNDI as DefaultDS
2017-03-16 09:28:06,961 [INFO] from play.api.db.DefaultDBApi in application-akka.actor.default-dispatcher-6 - Database [default] connected at jdbc:mysql://localhost/mavericks_project
2017-03-16 09:28:07,362 [INFO] from play.api.Play in application-akka.actor.default-dispatcher-6 - Application started (Dev)
2017-03-16 09:28:21,462 [DEBUG] from application in application-akka.actor.default-dispatcher-5 - 8c89693e6d0c58723140269f5cabf8e7281a0f1ad3b350f87f36f5c5e9c04945
2017-03-16 09:28:21,464 [DEBUG] from application in application-akka.actor.default-dispatcher-5 - ca95e65d9cba09c8b1058c89693e6d0c58723140269f5cabf8e7281a0f1ad3b350f87f36f5c5e9c04945s_akondi
2017-03-16 09:30:56,598 [INFO] from application in application-akka.actor.default-dispatcher-4 - Shutting down connection pool.
2017-03-16 09:30:56,815 [INFO] from application in application-akka.actor.default-dispatcher-4 - Creating Pool for datasource 'default'
2017-03-16 09:30:56,819 [INFO] from play.api.db.HikariCPConnectionPool in application-akka.actor.default-dispatcher-4 - datasource [default] bound to JNDI as DefaultDS
2017-03-16 09:30:56,822 [INFO] from play.api.db.DefaultDBApi in application-akka.actor.default-dispatcher-4 - Database [default] connected at jdbc:mysql://localhost/mavericks_project
2017-03-16 09:30:56,994 [INFO] from play.api.Play in application-akka.actor.default-dispatcher-4 - Application started (Dev)
2017-03-16 09:30:57,044 [INFO] from application in application-akka.actor.default-dispatcher-2 - Running AuthenticatorAction
2017-03-16 09:30:57,061 [DEBUG] from application in application-akka.actor.default-dispatcher-2 - Authorized header: null
2017-03-16 09:30:57,105 [ERROR] from application in application-akka.actor.default-dispatcher-2 - 

! @73c3kbc4h - Internal server error, for (PUT) [/update_members/46] ->
 
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[NullPointerException: null]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:293)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:220)
	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:160)
	at play.api.DefaultGlobal$.onError(GlobalSettings.scala:188)
	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:100)
	at play.filters.cors.AbstractCORSPolicy$$anonfun$2.applyOrElse(AbstractCORSPolicy.scala:146)
	at play.filters.cors.AbstractCORSPolicy$$anonfun$2.applyOrElse(AbstractCORSPolicy.scala:145)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:70)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248)
	at scala.concurrent.Promise$class.tryFailure(Promise.scala:112)
	at scala.concurrent.impl.Promise$DefaultPromise.tryFailure(Promise.scala:153)
	at play.api.mvc.Filter$$anon$1$$anonfun$apply$4$$anonfun$apply$1.applyOrElse(Filters.scala:83)
	at play.api.mvc.Filter$$anon$1$$anonfun$apply$4$$anonfun$apply$1.applyOrElse(Filters.scala:77)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:415)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.NullPointerException: null
	at controllers.security.AuthenticatorAction.call(AuthenticatorAction.java:32)
	at play.db.jpa.TransactionalAction.lambda$call$4(TransactionalAction.java:28)
	at play.db.jpa.DefaultJPAApi.lambda$withTransaction$3(DefaultJPAApi.java:196)
	at play.db.jpa.DefaultJPAApi.withTransaction(DefaultJPAApi.java:137)
	at play.db.jpa.DefaultJPAApi.withTransaction(DefaultJPAApi.java:195)
	at play.db.jpa.TransactionalAction.call(TransactionalAction.java:25)
	at play.core.j.JavaAction$$anonfun$7.apply(JavaAction.scala:108)
	at play.core.j.JavaAction$$anonfun$7.apply(JavaAction.scala:108)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:56)
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:70)
	at play.core.j.HttpExecutionContext.execute(HttpExecutionContext.scala:48)
	at scala.concurrent.impl.Future$.apply(Future.scala:31)
	at scala.concurrent.Future$.apply(Future.scala:492)
	at play.core.j.JavaAction.apply(JavaAction.scala:108)
	at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5$$anonfun$apply$6.apply(Action.scala:112)
	at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5$$anonfun$apply$6.apply(Action.scala:112)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
	at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5.apply(Action.scala:111)
	at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5.apply(Action.scala:110)
	at scala.Option.map(Option.scala:146)
	at play.api.mvc.Action$$anonfun$apply$2.apply(Action.scala:110)
	at play.api.mvc.Action$$anonfun$apply$2.apply(Action.scala:103)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249)
	... 13 common frames omitted
2017-03-16 09:33:03,588 [DEBUG] from application in application-akka.actor.default-dispatcher-5 - SELECT m from Member m where m.uname='s_akondi' 
2017-03-16 09:33:03,593 [DEBUG] from application in application-akka.actor.default-dispatcher-5 - [models.Member@57cffcd3]
2017-03-16 09:33:03,593 [DEBUG] from application in application-akka.actor.default-dispatcher-5 - 8c89693e6d0c58723140269f5cabf8e7281a0f1ad3b350f87f36f5c5e9c04945out
2017-03-16 09:33:03,593 [DEBUG] from application in application-akka.actor.default-dispatcher-5 - 8c89693e6d0c58723140269f5cabf8e7281a0f1ad3b350f87f36f5c5e9c04945out ex
2017-03-16 09:33:03,593 [DEBUG] from application in application-akka.actor.default-dispatcher-5 - 8c89693e6d0c58723140269f5cabf8e7281a0f1ad3b350f87f36f5c5e9c04945
2017-03-16 09:33:03,593 [DEBUG] from application in application-akka.actor.default-dispatcher-5 - 8c89693e6d0c58723140269f5cabf8e7281a0f1ad3b350f87f36f5c5e9c04945
2017-03-16 09:33:03,595 [DEBUG] from application in application-akka.actor.default-dispatcher-5 - auth:98f64b63-2af1-448e-86e9-5490fbeb38cc
2017-03-16 09:33:58,126 [INFO] from application in application-akka.actor.default-dispatcher-9 - Running AuthenticatorAction
2017-03-16 09:33:58,127 [DEBUG] from application in application-akka.actor.default-dispatcher-9 - Authorized header: Bearer 98f64b63-2af1-448e-86e9-5490fbeb38cc
2017-03-16 09:33:58,127 [DEBUG] from application in application-akka.actor.default-dispatcher-9 - auth_token: 98f64b63-2af1-448e-86e9-5490fbeb38cc
2017-03-16 09:33:58,127 [DEBUG] from application in application-akka.actor.default-dispatcher-9 - 98f64b63-2af1-448e-86e9-5490fbeb38cc
2017-03-16 09:33:58,127 [DEBUG] from application in application-akka.actor.default-dispatcher-9 - SELECT m FROM Member m where m.authToken='98f64b63-2af1-448e-86e9-5490fbeb38cc'
2017-03-16 09:33:58,129 [DEBUG] from application in application-akka.actor.default-dispatcher-9 - org.hibernate.jpa.internal.QueryImpl@31c535b5
2017-03-16 09:33:58,131 [DEBUG] from application in application-akka.actor.default-dispatcher-9 - [models.Member@5d89840b]
2017-03-16 09:33:58,131 [DEBUG] from application in application-akka.actor.default-dispatcher-9 - member: models.Member@5d89840b
2017-03-16 09:34:46,432 [INFO] from application in application-akka.actor.default-dispatcher-10 - Running AuthenticatorAction
2017-03-16 09:34:46,433 [DEBUG] from application in application-akka.actor.default-dispatcher-10 - Authorized header: Bearer 98f64b63-2af1-448e-86e9-5490fbeb38cc
2017-03-16 09:34:46,433 [DEBUG] from application in application-akka.actor.default-dispatcher-10 - auth_token: 98f64b63-2af1-448e-86e9-5490fbeb38cc
2017-03-16 09:34:46,433 [DEBUG] from application in application-akka.actor.default-dispatcher-10 - 98f64b63-2af1-448e-86e9-5490fbeb38cc
2017-03-16 09:34:46,433 [DEBUG] from application in application-akka.actor.default-dispatcher-10 - SELECT m FROM Member m where m.authToken='98f64b63-2af1-448e-86e9-5490fbeb38cc'
2017-03-16 09:34:46,433 [DEBUG] from application in application-akka.actor.default-dispatcher-10 - org.hibernate.jpa.internal.QueryImpl@5477fb84
2017-03-16 09:34:46,434 [DEBUG] from application in application-akka.actor.default-dispatcher-10 - [models.Member@2415c10f]
2017-03-16 09:34:46,434 [DEBUG] from application in application-akka.actor.default-dispatcher-10 - member: models.Member@2415c10f
2017-03-16 09:34:46,458 [DEBUG] from application in application-akka.actor.default-dispatcher-10 - 21
2017-03-16 09:36:21,379 [DEBUG] from application in application-akka.actor.default-dispatcher-13 - SELECT m from Member m where m.uname='sakondi' 
2017-03-16 09:36:21,383 [DEBUG] from application in application-akka.actor.default-dispatcher-13 - [models.Member@55de0457]
2017-03-16 09:36:21,383 [DEBUG] from application in application-akka.actor.default-dispatcher-13 - d1ef521d1a75eb1180aea02396958d6cee6bf82f9f885ca96e5d0a865a98d842out
2017-03-16 09:36:21,383 [DEBUG] from application in application-akka.actor.default-dispatcher-13 - d1ef521d1a75eb1180aea02396958d6cee6bf82f9f885ca96e5d0a865a98d842out ex
2017-03-16 09:36:21,383 [DEBUG] from application in application-akka.actor.default-dispatcher-13 - d1ef521d1a75eb1180aea02396958d6cee6bf82f9f885ca96e5d0a865a98d842
2017-03-16 09:36:21,383 [DEBUG] from application in application-akka.actor.default-dispatcher-13 - d1ef521d1a75eb1180aea02396958d6cee6bf82f9f885ca96e5d0a865a98d842
2017-03-16 09:36:21,383 [DEBUG] from application in application-akka.actor.default-dispatcher-13 - auth:96bfe88f-617f-4496-9cdf-ccf7e866ccc0
2017-03-16 09:39:11,201 [INFO] from application in application-akka.actor.default-dispatcher-21 - Running AuthenticatorAction
2017-03-16 09:39:11,202 [DEBUG] from application in application-akka.actor.default-dispatcher-21 - Authorized header: Bearer 96bfe88f-617f-4496-9cdf-ccf7e866ccc0
2017-03-16 09:39:11,202 [DEBUG] from application in application-akka.actor.default-dispatcher-21 - auth_token: 96bfe88f-617f-4496-9cdf-ccf7e866ccc0
2017-03-16 09:39:11,202 [DEBUG] from application in application-akka.actor.default-dispatcher-21 - 96bfe88f-617f-4496-9cdf-ccf7e866ccc0
2017-03-16 09:39:11,202 [DEBUG] from application in application-akka.actor.default-dispatcher-21 - SELECT m FROM Member m where m.authToken='96bfe88f-617f-4496-9cdf-ccf7e866ccc0'
2017-03-16 09:39:11,204 [DEBUG] from application in application-akka.actor.default-dispatcher-21 - org.hibernate.jpa.internal.QueryImpl@3b57dbfb
2017-03-16 09:39:11,205 [DEBUG] from application in application-akka.actor.default-dispatcher-21 - [models.Member@4a6c9cf8]
2017-03-16 09:39:11,205 [DEBUG] from application in application-akka.actor.default-dispatcher-21 - member: models.Member@4a6c9cf8
2017-03-16 09:40:37,101 [INFO] from application in application-akka.actor.default-dispatcher-22 - Running AuthenticatorAction
2017-03-16 09:40:37,101 [DEBUG] from application in application-akka.actor.default-dispatcher-22 - Authorized header: Bearer 4980bef9-a163-4eb7-801f-aa532f6cffc5
2017-03-16 09:40:37,101 [DEBUG] from application in application-akka.actor.default-dispatcher-22 - auth_token: 4980bef9-a163-4eb7-801f-aa532f6cffc5
2017-03-16 09:40:37,102 [DEBUG] from application in application-akka.actor.default-dispatcher-22 - 4980bef9-a163-4eb7-801f-aa532f6cffc5
2017-03-16 09:40:37,102 [DEBUG] from application in application-akka.actor.default-dispatcher-22 - SELECT m FROM Member m where m.authToken='4980bef9-a163-4eb7-801f-aa532f6cffc5'
2017-03-16 09:40:37,104 [DEBUG] from application in application-akka.actor.default-dispatcher-22 - org.hibernate.jpa.internal.QueryImpl@238d5d1d
2017-03-16 09:40:37,105 [DEBUG] from application in application-akka.actor.default-dispatcher-22 - [models.Member@43a2a252]
2017-03-16 09:40:37,105 [DEBUG] from application in application-akka.actor.default-dispatcher-22 - member: models.Member@43a2a252
2017-03-16 09:41:46,029 [INFO] from application in application-akka.actor.default-dispatcher-25 - Running AuthenticatorAction
2017-03-16 09:41:46,030 [DEBUG] from application in application-akka.actor.default-dispatcher-25 - Authorized header: Bearer e0deac22-cda0-41d5-ace8-51a6cbdf88fc
2017-03-16 09:41:46,030 [DEBUG] from application in application-akka.actor.default-dispatcher-25 - auth_token: e0deac22-cda0-41d5-ace8-51a6cbdf88fc
2017-03-16 09:41:46,030 [DEBUG] from application in application-akka.actor.default-dispatcher-25 - e0deac22-cda0-41d5-ace8-51a6cbdf88fc
2017-03-16 09:41:46,030 [DEBUG] from application in application-akka.actor.default-dispatcher-25 - SELECT m FROM Member m where m.authToken='e0deac22-cda0-41d5-ace8-51a6cbdf88fc'
2017-03-16 09:41:46,032 [DEBUG] from application in application-akka.actor.default-dispatcher-25 - org.hibernate.jpa.internal.QueryImpl@6a4dae40
2017-03-16 09:41:46,032 [DEBUG] from application in application-akka.actor.default-dispatcher-25 - [models.Member@19122038]
2017-03-16 09:41:46,033 [DEBUG] from application in application-akka.actor.default-dispatcher-25 - member: models.Member@19122038
2017-03-16 09:49:53,599 [DEBUG] from application in application-akka.actor.default-dispatcher-31 - 
2017-03-16 09:49:53,599 [DEBUG] from application in application-akka.actor.default-dispatcher-31 - 08:00:00
2017-03-16 09:49:53,599 [DEBUG] from application in application-akka.actor.default-dispatcher-31 - -
2017-03-16 09:51:32,908 [DEBUG] from application in application-akka.actor.default-dispatcher-34 - 
2017-03-16 09:51:32,908 [DEBUG] from application in application-akka.actor.default-dispatcher-34 - 08:00:00
2017-03-16 09:51:32,908 [DEBUG] from application in application-akka.actor.default-dispatcher-34 - -
2017-03-16 09:51:42,230 [DEBUG] from application in application-akka.actor.default-dispatcher-32 - 
2017-03-16 09:51:42,230 [DEBUG] from application in application-akka.actor.default-dispatcher-32 - 08:00:00
2017-03-16 09:51:42,230 [DEBUG] from application in application-akka.actor.default-dispatcher-32 - -
2017-03-16 09:56:57,055 [INFO] from application in application-akka.actor.default-dispatcher-36 - Shutting down connection pool.
2017-03-16 09:56:57,430 [INFO] from application in application-akka.actor.default-dispatcher-36 - Creating Pool for datasource 'default'
2017-03-16 09:56:57,434 [INFO] from play.api.db.HikariCPConnectionPool in application-akka.actor.default-dispatcher-36 - datasource [default] bound to JNDI as DefaultDS
2017-03-16 09:56:57,437 [INFO] from play.api.db.DefaultDBApi in application-akka.actor.default-dispatcher-36 - Database [default] connected at jdbc:mysql://localhost/mavericks_project
2017-03-16 09:56:57,628 [INFO] from play.api.Play in application-akka.actor.default-dispatcher-36 - Application started (Dev)
2017-03-16 09:57:26,106 [INFO] from application in application-akka.actor.default-dispatcher-2 - Shutting down connection pool.
2017-03-16 09:57:26,169 [INFO] from application in application-akka.actor.default-dispatcher-2 - Creating Pool for datasource 'default'
2017-03-16 09:57:26,172 [INFO] from play.api.db.HikariCPConnectionPool in application-akka.actor.default-dispatcher-2 - datasource [default] bound to JNDI as DefaultDS
2017-03-16 09:57:26,175 [INFO] from play.api.db.DefaultDBApi in application-akka.actor.default-dispatcher-2 - Database [default] connected at jdbc:mysql://localhost/mavericks_project
2017-03-16 09:57:26,378 [INFO] from play.api.Play in application-akka.actor.default-dispatcher-2 - Application started (Dev)
2017-03-16 10:20:10,608 [INFO] from application in application-akka.actor.default-dispatcher-4 - Shutting down connection pool.
2017-03-16 10:20:10,698 [INFO] from application in application-akka.actor.default-dispatcher-4 - Creating Pool for datasource 'default'
2017-03-16 10:20:10,702 [INFO] from play.api.db.HikariCPConnectionPool in application-akka.actor.default-dispatcher-4 - datasource [default] bound to JNDI as DefaultDS
2017-03-16 10:20:10,705 [INFO] from play.api.db.DefaultDBApi in application-akka.actor.default-dispatcher-4 - Database [default] connected at jdbc:mysql://localhost/mavericks_project
2017-03-16 10:20:10,956 [INFO] from play.api.Play in application-akka.actor.default-dispatcher-4 - Application started (Dev)
2017-03-16 10:21:34,555 [INFO] from application in application-akka.actor.default-dispatcher-7 - Shutting down connection pool.
2017-03-16 10:21:34,621 [INFO] from application in application-akka.actor.default-dispatcher-7 - Creating Pool for datasource 'default'
2017-03-16 10:21:34,625 [INFO] from play.api.db.HikariCPConnectionPool in application-akka.actor.default-dispatcher-7 - datasource [default] bound to JNDI as DefaultDS
2017-03-16 10:21:34,629 [INFO] from play.api.db.DefaultDBApi in application-akka.actor.default-dispatcher-7 - Database [default] connected at jdbc:mysql://localhost/mavericks_project
2017-03-16 10:21:34,781 [INFO] from play.api.Play in application-akka.actor.default-dispatcher-7 - Application started (Dev)
2017-03-16 10:22:40,288 [INFO] from application in application-akka.actor.default-dispatcher-3 - Shutting down connection pool.
2017-03-16 10:22:40,366 [INFO] from application in application-akka.actor.default-dispatcher-3 - Creating Pool for datasource 'default'
2017-03-16 10:22:40,369 [INFO] from play.api.db.HikariCPConnectionPool in application-akka.actor.default-dispatcher-3 - datasource [default] bound to JNDI as DefaultDS
2017-03-16 10:22:40,372 [INFO] from play.api.db.DefaultDBApi in application-akka.actor.default-dispatcher-3 - Database [default] connected at jdbc:mysql://localhost/mavericks_project
2017-03-16 10:22:40,529 [INFO] from play.api.Play in application-akka.actor.default-dispatcher-3 - Application started (Dev)
2017-03-16 10:26:07,861 [ERROR] from application in netty-event-loop-5 - 

! @73c41hkl1 - Internal server error, for (GET) [/arating_review_restaurant_users?id=1] ->
 
play.sbt.routes.RoutesCompilationException: Compilation error[string matching regex `\z' expected but `(' found]
	at play.sbt.routes.RoutesCompiler$$anonfun$9.apply(RoutesCompiler.scala:152)
	at play.sbt.routes.RoutesCompiler$$anonfun$9.apply(RoutesCompiler.scala:150)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at play.sbt.routes.RoutesCompiler$.compileRoutes(RoutesCompiler.scala:150)
	at play.sbt.routes.RoutesCompiler$$anonfun$4.apply(RoutesCompiler.scala:127)
	at play.sbt.routes.RoutesCompiler$$anonfun$4.apply(RoutesCompiler.scala:126)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2017-03-16 10:26:12,732 [ERROR] from application in netty-event-loop-5 - 

! @73c41i2o7 - Internal server error, for (GET) [/rating_review_restaurant_users?id=1] ->
 
play.sbt.routes.RoutesCompilationException: Compilation error[string matching regex `\z' expected but `(' found]
	at play.sbt.routes.RoutesCompiler$$anonfun$9.apply(RoutesCompiler.scala:152)
	at play.sbt.routes.RoutesCompiler$$anonfun$9.apply(RoutesCompiler.scala:150)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at play.sbt.routes.RoutesCompiler$.compileRoutes(RoutesCompiler.scala:150)
	at play.sbt.routes.RoutesCompiler$$anonfun$4.apply(RoutesCompiler.scala:127)
	at play.sbt.routes.RoutesCompiler$$anonfun$4.apply(RoutesCompiler.scala:126)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2017-03-16 10:26:31,826 [INFO] from application in application-akka.actor.default-dispatcher-3 - Shutting down connection pool.
2017-03-16 10:26:32,156 [INFO] from application in application-akka.actor.default-dispatcher-3 - Creating Pool for datasource 'default'
2017-03-16 10:26:32,159 [INFO] from play.api.db.HikariCPConnectionPool in application-akka.actor.default-dispatcher-3 - datasource [default] bound to JNDI as DefaultDS
2017-03-16 10:26:32,163 [INFO] from play.api.db.DefaultDBApi in application-akka.actor.default-dispatcher-3 - Database [default] connected at jdbc:mysql://localhost/mavericks_project
2017-03-16 10:26:32,458 [INFO] from play.api.Play in application-akka.actor.default-dispatcher-3 - Application started (Dev)
2017-03-16 10:27:05,804 [INFO] from application in application-akka.actor.default-dispatcher-3 - Running AuthenticatorAction
2017-03-16 10:27:05,804 [DEBUG] from application in application-akka.actor.default-dispatcher-3 - Authorized header: null
2017-03-16 10:27:05,806 [ERROR] from application in application-akka.actor.default-dispatcher-3 - 

! @73c41l3cj - Internal server error, for (GET) [/rating_by_currentuser?uname=manisha] ->
 
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[NullPointerException: null]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:293)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:220)
	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:160)
	at play.api.DefaultGlobal$.onError(GlobalSettings.scala:188)
	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:100)
	at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:100)
	at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:99)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:70)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248)
	at scala.concurrent.Promise$class.complete(Promise.scala:55)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153)
	at scala.concurrent.Future$$anonfun$recoverWith$1$$anonfun$apply$6.apply(Future.scala:344)
	at scala.concurrent.Future$$anonfun$recoverWith$1$$anonfun$apply$6.apply(Future.scala:344)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.processBatch$1(BatchingExecutor.scala:63)
	at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:78)
	at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:55)
	at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:55)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at scala.concurrent.BatchingExecutor$Batch.run(BatchingExecutor.scala:54)
	at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:599)
	at scala.concurrent.BatchingExecutor$class.execute(BatchingExecutor.scala:106)
	at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:597)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
	at scala.concurrent.impl.Promise$DefaultPromise.scala$concurrent$impl$Promise$DefaultPromise$$dispatchOrAddCallback(Promise.scala:280)
	at scala.concurrent.impl.Promise$DefaultPromise.onComplete(Promise.scala:270)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:415)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.NullPointerException: null
	at controllers.security.AuthenticatorAction.call(AuthenticatorAction.java:32)
	at play.db.jpa.TransactionalAction.lambda$call$4(TransactionalAction.java:28)
	at play.db.jpa.DefaultJPAApi.lambda$withTransaction$3(DefaultJPAApi.java:196)
	at play.db.jpa.DefaultJPAApi.withTransaction(DefaultJPAApi.java:137)
	at play.db.jpa.DefaultJPAApi.withTransaction(DefaultJPAApi.java:195)
	at play.db.jpa.TransactionalAction.call(TransactionalAction.java:25)
	at play.core.j.JavaAction$$anonfun$7.apply(JavaAction.scala:108)
	at play.core.j.JavaAction$$anonfun$7.apply(JavaAction.scala:108)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:56)
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:70)
	at play.core.j.HttpExecutionContext.execute(HttpExecutionContext.scala:48)
	at scala.concurrent.impl.Future$.apply(Future.scala:31)
	at scala.concurrent.Future$.apply(Future.scala:492)
	at play.core.j.JavaAction.apply(JavaAction.scala:108)
	at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5$$anonfun$apply$6.apply(Action.scala:112)
	at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5$$anonfun$apply$6.apply(Action.scala:112)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
	at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5.apply(Action.scala:111)
	at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5.apply(Action.scala:110)
	at scala.Option.map(Option.scala:146)
	at play.api.mvc.Action$$anonfun$apply$2.apply(Action.scala:110)
	at play.api.mvc.Action$$anonfun$apply$2.apply(Action.scala:103)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249)
	... 13 common frames omitted
2017-03-16 10:27:46,014 [INFO] from application in application-akka.actor.default-dispatcher-7 - Running AuthenticatorAction
2017-03-16 10:27:46,014 [DEBUG] from application in application-akka.actor.default-dispatcher-7 - Authorized header: Bearer 4980bef9-a163-4eb7-801f-aa532f6cffc5
2017-03-16 10:27:46,014 [DEBUG] from application in application-akka.actor.default-dispatcher-7 - auth_token: 4980bef9-a163-4eb7-801f-aa532f6cffc5
2017-03-16 10:27:46,015 [DEBUG] from application in application-akka.actor.default-dispatcher-7 - 4980bef9-a163-4eb7-801f-aa532f6cffc5
2017-03-16 10:27:46,015 [DEBUG] from application in application-akka.actor.default-dispatcher-7 - SELECT m FROM Member m where m.authToken='4980bef9-a163-4eb7-801f-aa532f6cffc5'
2017-03-16 10:27:46,019 [DEBUG] from application in application-akka.actor.default-dispatcher-7 - org.hibernate.jpa.internal.QueryImpl@37ee0749
2017-03-16 10:27:46,020 [DEBUG] from application in application-akka.actor.default-dispatcher-7 - [models.Member@4477dd8]
2017-03-16 10:27:46,020 [DEBUG] from application in application-akka.actor.default-dispatcher-7 - member: models.Member@4477dd8
2017-03-16 10:31:47,412 [DEBUG] from application in application-akka.actor.default-dispatcher-10 - 
2017-03-16 10:31:47,412 [DEBUG] from application in application-akka.actor.default-dispatcher-10 - 08:00:00
2017-03-16 10:31:47,412 [DEBUG] from application in application-akka.actor.default-dispatcher-10 - -
2017-03-16 10:32:07,711 [DEBUG] from application in application-akka.actor.default-dispatcher-12 - 
2017-03-16 10:32:07,711 [DEBUG] from application in application-akka.actor.default-dispatcher-12 - 08:00:00
2017-03-16 10:32:07,711 [DEBUG] from application in application-akka.actor.default-dispatcher-12 - -
2017-03-16 10:48:18,941 [INFO] from application in application-akka.actor.default-dispatcher-17 - Running AuthenticatorAction
2017-03-16 10:48:18,942 [DEBUG] from application in application-akka.actor.default-dispatcher-17 - Authorized header: Bearer 4980bef9-a163-4eb7-801f-aa532f6cffc5
2017-03-16 10:48:18,942 [DEBUG] from application in application-akka.actor.default-dispatcher-17 - auth_token: 4980bef9-a163-4eb7-801f-aa532f6cffc5
2017-03-16 10:48:18,942 [DEBUG] from application in application-akka.actor.default-dispatcher-17 - 4980bef9-a163-4eb7-801f-aa532f6cffc5
2017-03-16 10:48:18,942 [DEBUG] from application in application-akka.actor.default-dispatcher-17 - SELECT m FROM Member m where m.authToken='4980bef9-a163-4eb7-801f-aa532f6cffc5'
2017-03-16 10:48:18,942 [DEBUG] from application in application-akka.actor.default-dispatcher-17 - org.hibernate.jpa.internal.QueryImpl@64a85bf5
2017-03-16 10:48:18,943 [DEBUG] from application in application-akka.actor.default-dispatcher-17 - [models.Member@14fa961f]
2017-03-16 10:48:18,943 [DEBUG] from application in application-akka.actor.default-dispatcher-17 - member: models.Member@14fa961f
2017-03-16 11:08:43,287 [WARN] from com.zaxxer.hikari.pool.HikariPool in HikariPool-9 housekeeper - HikariPool-9 - Thread starvation or clock leap detected (housekeeper delta=4m33s666ms).
2017-03-16 11:17:52,584 [INFO] from application in application-akka.actor.default-dispatcher-23 - Running AuthenticatorAction
2017-03-16 11:17:52,585 [DEBUG] from application in application-akka.actor.default-dispatcher-23 - Authorized header: null
2017-03-16 11:17:52,586 [ERROR] from application in application-akka.actor.default-dispatcher-23 - 

! @73c48ccef - Internal server error, for (GET) [/rating_by_currentuser?uname=manisha] ->
 
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[NullPointerException: null]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:293)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:220)
	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:160)
	at play.api.DefaultGlobal$.onError(GlobalSettings.scala:188)
	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:100)
	at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:100)
	at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:99)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:70)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248)
	at scala.concurrent.Promise$class.complete(Promise.scala:55)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153)
	at scala.concurrent.Future$$anonfun$recoverWith$1$$anonfun$apply$6.apply(Future.scala:344)
	at scala.concurrent.Future$$anonfun$recoverWith$1$$anonfun$apply$6.apply(Future.scala:344)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.processBatch$1(BatchingExecutor.scala:63)
	at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:78)
	at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:55)
	at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:55)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at scala.concurrent.BatchingExecutor$Batch.run(BatchingExecutor.scala:54)
	at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:599)
	at scala.concurrent.BatchingExecutor$class.execute(BatchingExecutor.scala:106)
	at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:597)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
	at scala.concurrent.impl.Promise$DefaultPromise.scala$concurrent$impl$Promise$DefaultPromise$$dispatchOrAddCallback(Promise.scala:280)
	at scala.concurrent.impl.Promise$DefaultPromise.onComplete(Promise.scala:270)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:415)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.NullPointerException: null
	at controllers.security.AuthenticatorAction.call(AuthenticatorAction.java:32)
	at play.db.jpa.TransactionalAction.lambda$call$4(TransactionalAction.java:28)
	at play.db.jpa.DefaultJPAApi.lambda$withTransaction$3(DefaultJPAApi.java:196)
	at play.db.jpa.DefaultJPAApi.withTransaction(DefaultJPAApi.java:137)
	at play.db.jpa.DefaultJPAApi.withTransaction(DefaultJPAApi.java:195)
	at play.db.jpa.TransactionalAction.call(TransactionalAction.java:25)
	at play.core.j.JavaAction$$anonfun$7.apply(JavaAction.scala:108)
	at play.core.j.JavaAction$$anonfun$7.apply(JavaAction.scala:108)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:56)
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:70)
	at play.core.j.HttpExecutionContext.execute(HttpExecutionContext.scala:48)
	at scala.concurrent.impl.Future$.apply(Future.scala:31)
	at scala.concurrent.Future$.apply(Future.scala:492)
	at play.core.j.JavaAction.apply(JavaAction.scala:108)
	at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5$$anonfun$apply$6.apply(Action.scala:112)
	at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5$$anonfun$apply$6.apply(Action.scala:112)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
	at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5.apply(Action.scala:111)
	at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5.apply(Action.scala:110)
	at scala.Option.map(Option.scala:146)
	at play.api.mvc.Action$$anonfun$apply$2.apply(Action.scala:110)
	at play.api.mvc.Action$$anonfun$apply$2.apply(Action.scala:103)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249)
	... 13 common frames omitted
2017-03-16 11:18:33,416 [INFO] from application in application-akka.actor.default-dispatcher-26 - Running AuthenticatorAction
2017-03-16 11:18:33,416 [DEBUG] from application in application-akka.actor.default-dispatcher-26 - Authorized header: Bearer 4980bef9-a163-4eb7-801f-aa532f6cffc5
2017-03-16 11:18:33,416 [DEBUG] from application in application-akka.actor.default-dispatcher-26 - auth_token: 4980bef9-a163-4eb7-801f-aa532f6cffc5
2017-03-16 11:18:33,416 [DEBUG] from application in application-akka.actor.default-dispatcher-26 - 4980bef9-a163-4eb7-801f-aa532f6cffc5
2017-03-16 11:18:33,416 [DEBUG] from application in application-akka.actor.default-dispatcher-26 - SELECT m FROM Member m where m.authToken='4980bef9-a163-4eb7-801f-aa532f6cffc5'
2017-03-16 11:18:33,416 [DEBUG] from application in application-akka.actor.default-dispatcher-26 - org.hibernate.jpa.internal.QueryImpl@6d3d26d0
2017-03-16 11:18:33,417 [DEBUG] from application in application-akka.actor.default-dispatcher-26 - [models.Member@1de6e7d3]
2017-03-16 11:18:33,417 [DEBUG] from application in application-akka.actor.default-dispatcher-26 - member: models.Member@1de6e7d3
2017-03-16 11:23:42,670 [WARN] from com.zaxxer.hikari.pool.HikariPool in HikariPool-9 housekeeper - HikariPool-9 - Retrograde clock change detected (housekeeper delta=29s299ms), soft-evicting connections from pool.
2017-03-16 11:55:58,123 [INFO] from application in application-akka.actor.default-dispatcher-27 - Shutting down connection pool.
2017-03-16 11:55:58,200 [INFO] from application in application-akka.actor.default-dispatcher-27 - Creating Pool for datasource 'default'
2017-03-16 11:55:58,204 [INFO] from play.api.db.HikariCPConnectionPool in application-akka.actor.default-dispatcher-27 - datasource [default] bound to JNDI as DefaultDS
2017-03-16 11:55:58,208 [INFO] from play.api.db.DefaultDBApi in application-akka.actor.default-dispatcher-27 - Database [default] connected at jdbc:mysql://localhost/mavericks_project
2017-03-16 11:55:58,415 [INFO] from play.api.Play in application-akka.actor.default-dispatcher-27 - Application started (Dev)
2017-03-16 11:55:58,428 [INFO] from application in application-akka.actor.default-dispatcher-4 - Running AuthenticatorAction
2017-03-16 11:55:58,428 [DEBUG] from application in application-akka.actor.default-dispatcher-4 - Authorized header: Bearer 4980bef9-a163-4eb7-801f-aa532f6cffc5
2017-03-16 11:55:58,428 [DEBUG] from application in application-akka.actor.default-dispatcher-4 - auth_token: 4980bef9-a163-4eb7-801f-aa532f6cffc5
2017-03-16 11:55:58,428 [DEBUG] from application in application-akka.actor.default-dispatcher-4 - 4980bef9-a163-4eb7-801f-aa532f6cffc5
2017-03-16 11:55:58,428 [DEBUG] from application in application-akka.actor.default-dispatcher-4 - SELECT m FROM Member m where m.authToken='4980bef9-a163-4eb7-801f-aa532f6cffc5'
2017-03-16 11:55:58,431 [DEBUG] from application in application-akka.actor.default-dispatcher-4 - org.hibernate.jpa.internal.QueryImpl@8234ef8
2017-03-16 11:55:58,432 [DEBUG] from application in application-akka.actor.default-dispatcher-4 - [models.Member@132762cb]
2017-03-16 11:55:58,432 [DEBUG] from application in application-akka.actor.default-dispatcher-4 - member: models.Member@132762cb
2017-03-16 11:57:35,992 [INFO] from application in application-akka.actor.default-dispatcher-3 - Shutting down connection pool.
2017-03-16 11:57:36,053 [INFO] from application in application-akka.actor.default-dispatcher-3 - Creating Pool for datasource 'default'
2017-03-16 11:57:36,056 [INFO] from play.api.db.HikariCPConnectionPool in application-akka.actor.default-dispatcher-3 - datasource [default] bound to JNDI as DefaultDS
2017-03-16 11:57:36,060 [INFO] from play.api.db.DefaultDBApi in application-akka.actor.default-dispatcher-3 - Database [default] connected at jdbc:mysql://localhost/mavericks_project
2017-03-16 11:57:36,336 [INFO] from play.api.Play in application-akka.actor.default-dispatcher-3 - Application started (Dev)
2017-03-16 11:57:36,359 [INFO] from application in application-akka.actor.default-dispatcher-9 - Running AuthenticatorAction
2017-03-16 11:57:36,360 [DEBUG] from application in application-akka.actor.default-dispatcher-9 - Authorized header: Bearer 4980bef9-a163-4eb7-801f-aa532f6cffc5
2017-03-16 11:57:36,360 [DEBUG] from application in application-akka.actor.default-dispatcher-9 - auth_token: 4980bef9-a163-4eb7-801f-aa532f6cffc5
2017-03-16 11:57:36,360 [DEBUG] from application in application-akka.actor.default-dispatcher-9 - 4980bef9-a163-4eb7-801f-aa532f6cffc5
2017-03-16 11:57:36,360 [DEBUG] from application in application-akka.actor.default-dispatcher-9 - SELECT m FROM Member m where m.authToken='4980bef9-a163-4eb7-801f-aa532f6cffc5'
2017-03-16 11:57:36,362 [DEBUG] from application in application-akka.actor.default-dispatcher-9 - org.hibernate.jpa.internal.QueryImpl@34e9eda4
2017-03-16 11:57:36,363 [DEBUG] from application in application-akka.actor.default-dispatcher-9 - [models.Member@2fed4408]
2017-03-16 11:57:36,363 [DEBUG] from application in application-akka.actor.default-dispatcher-9 - member: models.Member@2fed4408
2017-03-16 11:57:36,367 [ERROR] from application in application-akka.actor.default-dispatcher-9 - 

! @73c4di2mc - Internal server error, for (GET) [/ratings_reviews?id=1] ->
 
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[PersistenceException: org.hibernate.loader.custom.NonUniqueDiscoveredSqlAliasException: Encountered a duplicated sql alias [id] during auto-discovery of a native-sql query]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:293)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:220)
	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:160)
	at play.api.DefaultGlobal$.onError(GlobalSettings.scala:188)
	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:100)
	at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:100)
	at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:99)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:70)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248)
	at scala.concurrent.Promise$class.complete(Promise.scala:55)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153)
	at scala.concurrent.Future$$anonfun$recoverWith$1$$anonfun$apply$6.apply(Future.scala:344)
	at scala.concurrent.Future$$anonfun$recoverWith$1$$anonfun$apply$6.apply(Future.scala:344)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.processBatch$1(BatchingExecutor.scala:63)
	at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:78)
	at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:55)
	at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:55)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at scala.concurrent.BatchingExecutor$Batch.run(BatchingExecutor.scala:54)
	at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:599)
	at scala.concurrent.BatchingExecutor$class.execute(BatchingExecutor.scala:106)
	at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:597)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
	at scala.concurrent.impl.Promise$DefaultPromise.scala$concurrent$impl$Promise$DefaultPromise$$dispatchOrAddCallback(Promise.scala:280)
	at scala.concurrent.impl.Promise$DefaultPromise.onComplete(Promise.scala:270)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:415)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: javax.persistence.PersistenceException: org.hibernate.loader.custom.NonUniqueDiscoveredSqlAliasException: Encountered a duplicated sql alias [id] during auto-discovery of a native-sql query
	at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1692)
	at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1602)
	at org.hibernate.jpa.internal.QueryImpl.getResultList(QueryImpl.java:492)
	at controllers.RestaurantController.Reviews_Ratings_Restaurant(RestaurantController.java:252)
	at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$32$$anonfun$apply$32.apply(Routes.scala:846)
	at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$32$$anonfun$apply$32.apply(Routes.scala:846)
	at play.core.routing.HandlerInvokerFactory$$anon$4.resultCall(HandlerInvoker.scala:157)
	at play.core.routing.HandlerInvokerFactory$$anon$4.resultCall(HandlerInvoker.scala:156)
	at play.core.routing.HandlerInvokerFactory$JavaActionInvokerFactory$$anon$14$$anon$3$$anon$1.invocation(HandlerInvoker.scala:136)
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:73)
	at play.http.HttpRequestHandler$1.call(HttpRequestHandler.java:54)
	at controllers.security.AuthenticatorAction.call(AuthenticatorAction.java:52)
	at play.db.jpa.TransactionalAction.lambda$call$4(TransactionalAction.java:28)
	at play.db.jpa.DefaultJPAApi.lambda$withTransaction$3(DefaultJPAApi.java:196)
	at play.db.jpa.DefaultJPAApi.withTransaction(DefaultJPAApi.java:137)
	at play.db.jpa.DefaultJPAApi.withTransaction(DefaultJPAApi.java:195)
	at play.db.jpa.TransactionalAction.call(TransactionalAction.java:25)
	at play.core.j.JavaAction$$anonfun$7.apply(JavaAction.scala:108)
	at play.core.j.JavaAction$$anonfun$7.apply(JavaAction.scala:108)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:56)
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:70)
	at play.core.j.HttpExecutionContext.execute(HttpExecutionContext.scala:48)
	at scala.concurrent.impl.Future$.apply(Future.scala:31)
	at scala.concurrent.Future$.apply(Future.scala:492)
	at play.core.j.JavaAction.apply(JavaAction.scala:108)
	at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5$$anonfun$apply$6.apply(Action.scala:112)
	at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5$$anonfun$apply$6.apply(Action.scala:112)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
	at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5.apply(Action.scala:111)
	at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5.apply(Action.scala:110)
	at scala.Option.map(Option.scala:146)
	at play.api.mvc.Action$$anonfun$apply$2.apply(Action.scala:110)
	at play.api.mvc.Action$$anonfun$apply$2.apply(Action.scala:103)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249)
	... 13 common frames omitted
Caused by: org.hibernate.loader.custom.NonUniqueDiscoveredSqlAliasException: Encountered a duplicated sql alias [id] during auto-discovery of a native-sql query
	at org.hibernate.loader.custom.CustomLoader.validateAliases(CustomLoader.java:513)
	at org.hibernate.loader.custom.CustomLoader.autoDiscoverTypes(CustomLoader.java:490)
	at org.hibernate.loader.Loader.getResultSet(Loader.java:2123)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1898)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1874)
	at org.hibernate.loader.Loader.doQuery(Loader.java:919)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:336)
	at org.hibernate.loader.Loader.doList(Loader.java:2610)
	at org.hibernate.loader.Loader.doList(Loader.java:2593)
	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2422)
	at org.hibernate.loader.Loader.list(Loader.java:2417)
	at org.hibernate.loader.custom.CustomLoader.list(CustomLoader.java:336)
	at org.hibernate.internal.SessionImpl.listCustomQuery(SessionImpl.java:1980)
	at org.hibernate.internal.AbstractSessionImpl.list(AbstractSessionImpl.java:322)
	at org.hibernate.internal.SQLQueryImpl.list(SQLQueryImpl.java:125)
	at org.hibernate.jpa.internal.QueryImpl.list(QueryImpl.java:606)
	at org.hibernate.jpa.internal.QueryImpl.getResultList(QueryImpl.java:483)
	... 47 common frames omitted
2017-03-16 11:59:15,016 [INFO] from application in application-akka.actor.default-dispatcher-6 - Shutting down connection pool.
2017-03-16 11:59:15,075 [INFO] from application in application-akka.actor.default-dispatcher-6 - Creating Pool for datasource 'default'
2017-03-16 11:59:15,077 [INFO] from play.api.db.HikariCPConnectionPool in application-akka.actor.default-dispatcher-6 - datasource [default] bound to JNDI as DefaultDS
2017-03-16 11:59:15,081 [INFO] from play.api.db.DefaultDBApi in application-akka.actor.default-dispatcher-6 - Database [default] connected at jdbc:mysql://localhost/mavericks_project
2017-03-16 11:59:15,222 [INFO] from play.api.Play in application-akka.actor.default-dispatcher-6 - Application started (Dev)
2017-03-16 11:59:15,234 [INFO] from application in application-akka.actor.default-dispatcher-5 - Running AuthenticatorAction
2017-03-16 11:59:15,234 [DEBUG] from application in application-akka.actor.default-dispatcher-5 - Authorized header: Bearer 4980bef9-a163-4eb7-801f-aa532f6cffc5
2017-03-16 11:59:15,234 [DEBUG] from application in application-akka.actor.default-dispatcher-5 - auth_token: 4980bef9-a163-4eb7-801f-aa532f6cffc5
2017-03-16 11:59:15,234 [DEBUG] from application in application-akka.actor.default-dispatcher-5 - 4980bef9-a163-4eb7-801f-aa532f6cffc5
2017-03-16 11:59:15,234 [DEBUG] from application in application-akka.actor.default-dispatcher-5 - SELECT m FROM Member m where m.authToken='4980bef9-a163-4eb7-801f-aa532f6cffc5'
2017-03-16 11:59:15,236 [DEBUG] from application in application-akka.actor.default-dispatcher-5 - org.hibernate.jpa.internal.QueryImpl@57fbb856
2017-03-16 11:59:15,237 [DEBUG] from application in application-akka.actor.default-dispatcher-5 - [models.Member@4cff754e]
2017-03-16 11:59:15,237 [DEBUG] from application in application-akka.actor.default-dispatcher-5 - member: models.Member@4cff754e
2017-03-16 11:59:15,307 [WARN] from org.hibernate.engine.jdbc.spi.SqlExceptionHelper in application-akka.actor.default-dispatcher-5 - SQL Error: 1054, SQLState: 42S22
2017-03-16 11:59:15,307 [ERROR] from org.hibernate.engine.jdbc.spi.SqlExceptionHelper in application-akka.actor.default-dispatcher-5 - Unknown column 'tb_ratings.id' in 'field list'
2017-03-16 11:59:15,314 [ERROR] from application in application-akka.actor.default-dispatcher-5 - 

! @73c4dnj62 - Internal server error, for (GET) [/ratings_reviews?id=1] ->
 
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[PersistenceException: org.hibernate.exception.SQLGrammarException: could not extract ResultSet]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:293)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:220)
	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:160)
	at play.api.DefaultGlobal$.onError(GlobalSettings.scala:188)
	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:100)
	at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:100)
	at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:99)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:70)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248)
	at scala.concurrent.Promise$class.complete(Promise.scala:55)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153)
	at scala.concurrent.Future$$anonfun$recoverWith$1$$anonfun$apply$6.apply(Future.scala:344)
	at scala.concurrent.Future$$anonfun$recoverWith$1$$anonfun$apply$6.apply(Future.scala:344)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.processBatch$1(BatchingExecutor.scala:63)
	at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:78)
	at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:55)
	at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:55)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at scala.concurrent.BatchingExecutor$Batch.run(BatchingExecutor.scala:54)
	at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:599)
	at scala.concurrent.BatchingExecutor$class.execute(BatchingExecutor.scala:106)
	at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:597)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
	at scala.concurrent.impl.Promise$DefaultPromise.scala$concurrent$impl$Promise$DefaultPromise$$dispatchOrAddCallback(Promise.scala:280)
	at scala.concurrent.impl.Promise$DefaultPromise.onComplete(Promise.scala:270)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:415)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: javax.persistence.PersistenceException: org.hibernate.exception.SQLGrammarException: could not extract ResultSet
	at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1692)
	at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1602)
	at org.hibernate.jpa.internal.QueryImpl.getResultList(QueryImpl.java:492)
	at controllers.RestaurantController.Reviews_Ratings_Restaurant(RestaurantController.java:252)
	at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$32$$anonfun$apply$32.apply(Routes.scala:846)
	at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$32$$anonfun$apply$32.apply(Routes.scala:846)
	at play.core.routing.HandlerInvokerFactory$$anon$4.resultCall(HandlerInvoker.scala:157)
	at play.core.routing.HandlerInvokerFactory$$anon$4.resultCall(HandlerInvoker.scala:156)
	at play.core.routing.HandlerInvokerFactory$JavaActionInvokerFactory$$anon$14$$anon$3$$anon$1.invocation(HandlerInvoker.scala:136)
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:73)
	at play.http.HttpRequestHandler$1.call(HttpRequestHandler.java:54)
	at controllers.security.AuthenticatorAction.call(AuthenticatorAction.java:52)
	at play.db.jpa.TransactionalAction.lambda$call$4(TransactionalAction.java:28)
	at play.db.jpa.DefaultJPAApi.lambda$withTransaction$3(DefaultJPAApi.java:196)
	at play.db.jpa.DefaultJPAApi.withTransaction(DefaultJPAApi.java:137)
	at play.db.jpa.DefaultJPAApi.withTransaction(DefaultJPAApi.java:195)
	at play.db.jpa.TransactionalAction.call(TransactionalAction.java:25)
	at play.core.j.JavaAction$$anonfun$7.apply(JavaAction.scala:108)
	at play.core.j.JavaAction$$anonfun$7.apply(JavaAction.scala:108)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:56)
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:70)
	at play.core.j.HttpExecutionContext.execute(HttpExecutionContext.scala:48)
	at scala.concurrent.impl.Future$.apply(Future.scala:31)
	at scala.concurrent.Future$.apply(Future.scala:492)
	at play.core.j.JavaAction.apply(JavaAction.scala:108)
	at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5$$anonfun$apply$6.apply(Action.scala:112)
	at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5$$anonfun$apply$6.apply(Action.scala:112)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
	at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5.apply(Action.scala:111)
	at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5.apply(Action.scala:110)
	at scala.Option.map(Option.scala:146)
	at play.api.mvc.Action$$anonfun$apply$2.apply(Action.scala:110)
	at play.api.mvc.Action$$anonfun$apply$2.apply(Action.scala:103)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249)
	... 13 common frames omitted
Caused by: org.hibernate.exception.SQLGrammarException: could not extract ResultSet
	at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:63)
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:111)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:97)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:79)
	at org.hibernate.loader.Loader.getResultSet(Loader.java:2115)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1898)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1874)
	at org.hibernate.loader.Loader.doQuery(Loader.java:919)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:336)
	at org.hibernate.loader.Loader.doList(Loader.java:2610)
	at org.hibernate.loader.Loader.doList(Loader.java:2593)
	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2422)
	at org.hibernate.loader.Loader.list(Loader.java:2417)
	at org.hibernate.loader.custom.CustomLoader.list(CustomLoader.java:336)
	at org.hibernate.internal.SessionImpl.listCustomQuery(SessionImpl.java:1980)
	at org.hibernate.internal.AbstractSessionImpl.list(AbstractSessionImpl.java:322)
	at org.hibernate.internal.SQLQueryImpl.list(SQLQueryImpl.java:125)
	at org.hibernate.jpa.internal.QueryImpl.list(QueryImpl.java:606)
	at org.hibernate.jpa.internal.QueryImpl.getResultList(QueryImpl.java:483)
	... 47 common frames omitted
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'tb_ratings.id' in 'field list'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:400)
	at com.mysql.jdbc.Util.getInstance(Util.java:383)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:980)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3847)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3783)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2447)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2594)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2545)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1901)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2002)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:70)
	... 62 common frames omitted
2017-03-16 11:59:36,070 [INFO] from application in application-akka.actor.default-dispatcher-2 - Shutting down connection pool.
2017-03-16 11:59:36,123 [INFO] from application in application-akka.actor.default-dispatcher-2 - Creating Pool for datasource 'default'
2017-03-16 11:59:36,126 [INFO] from play.api.db.HikariCPConnectionPool in application-akka.actor.default-dispatcher-2 - datasource [default] bound to JNDI as DefaultDS
2017-03-16 11:59:36,129 [INFO] from play.api.db.DefaultDBApi in application-akka.actor.default-dispatcher-2 - Database [default] connected at jdbc:mysql://localhost/mavericks_project
2017-03-16 11:59:36,270 [INFO] from play.api.Play in application-akka.actor.default-dispatcher-2 - Application started (Dev)
2017-03-16 11:59:36,281 [INFO] from application in application-akka.actor.default-dispatcher-4 - Running AuthenticatorAction
2017-03-16 11:59:36,282 [DEBUG] from application in application-akka.actor.default-dispatcher-4 - Authorized header: Bearer 4980bef9-a163-4eb7-801f-aa532f6cffc5
2017-03-16 11:59:36,282 [DEBUG] from application in application-akka.actor.default-dispatcher-4 - auth_token: 4980bef9-a163-4eb7-801f-aa532f6cffc5
2017-03-16 11:59:36,282 [DEBUG] from application in application-akka.actor.default-dispatcher-4 - 4980bef9-a163-4eb7-801f-aa532f6cffc5
2017-03-16 11:59:36,282 [DEBUG] from application in application-akka.actor.default-dispatcher-4 - SELECT m FROM Member m where m.authToken='4980bef9-a163-4eb7-801f-aa532f6cffc5'
2017-03-16 11:59:36,283 [DEBUG] from application in application-akka.actor.default-dispatcher-4 - org.hibernate.jpa.internal.QueryImpl@6e49cad9
2017-03-16 11:59:36,284 [DEBUG] from application in application-akka.actor.default-dispatcher-4 - [models.Member@754d0626]
2017-03-16 11:59:36,285 [DEBUG] from application in application-akka.actor.default-dispatcher-4 - member: models.Member@754d0626
2017-03-16 12:25:23,864 [INFO] from application in application-akka.actor.default-dispatcher-3 - Shutting down connection pool.
2017-03-16 12:25:23,920 [INFO] from application in application-akka.actor.default-dispatcher-3 - Creating Pool for datasource 'default'
2017-03-16 12:25:23,924 [INFO] from play.api.db.HikariCPConnectionPool in application-akka.actor.default-dispatcher-3 - datasource [default] bound to JNDI as DefaultDS
2017-03-16 12:25:23,927 [INFO] from play.api.db.DefaultDBApi in application-akka.actor.default-dispatcher-3 - Database [default] connected at jdbc:mysql://localhost/mavericks_project
2017-03-16 12:25:24,129 [INFO] from play.api.Play in application-akka.actor.default-dispatcher-3 - Application started (Dev)
2017-03-16 13:14:45,328 [INFO] from application in application-akka.actor.default-dispatcher-6 - Shutting down connection pool.
2017-03-16 13:14:45,393 [INFO] from application in application-akka.actor.default-dispatcher-6 - Creating Pool for datasource 'default'
2017-03-16 13:14:45,396 [INFO] from play.api.db.HikariCPConnectionPool in application-akka.actor.default-dispatcher-6 - datasource [default] bound to JNDI as DefaultDS
2017-03-16 13:14:45,399 [INFO] from play.api.db.DefaultDBApi in application-akka.actor.default-dispatcher-6 - Database [default] connected at jdbc:mysql://localhost/mavericks_project
2017-03-16 13:14:45,685 [INFO] from play.api.Play in application-akka.actor.default-dispatcher-6 - Application started (Dev)
2017-03-16 13:14:45,695 [ERROR] from application in application-akka.actor.default-dispatcher-4 - 

! @73c4nlcpe - Internal server error, for (GET) [/avg_rating_restaurant?id=1] ->
 
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[PersistenceException: org.hibernate.loader.custom.NonUniqueDiscoveredSqlAliasException: Encountered a duplicated sql alias [Avg_Rating] during auto-discovery of a native-sql query]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:293)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:220)
	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:160)
	at play.api.DefaultGlobal$.onError(GlobalSettings.scala:188)
	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:100)
	at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:100)
	at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:99)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:70)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248)
	at scala.concurrent.Promise$class.complete(Promise.scala:55)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153)
	at scala.concurrent.Future$$anonfun$recoverWith$1$$anonfun$apply$6.apply(Future.scala:344)
	at scala.concurrent.Future$$anonfun$recoverWith$1$$anonfun$apply$6.apply(Future.scala:344)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.processBatch$1(BatchingExecutor.scala:63)
	at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:78)
	at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:55)
	at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:55)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at scala.concurrent.BatchingExecutor$Batch.run(BatchingExecutor.scala:54)
	at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:599)
	at scala.concurrent.BatchingExecutor$class.execute(BatchingExecutor.scala:106)
	at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:597)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
	at scala.concurrent.impl.Promise$DefaultPromise.scala$concurrent$impl$Promise$DefaultPromise$$dispatchOrAddCallback(Promise.scala:280)
	at scala.concurrent.impl.Promise$DefaultPromise.onComplete(Promise.scala:270)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:415)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: javax.persistence.PersistenceException: org.hibernate.loader.custom.NonUniqueDiscoveredSqlAliasException: Encountered a duplicated sql alias [Avg_Rating] during auto-discovery of a native-sql query
	at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1692)
	at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1602)
	at org.hibernate.jpa.internal.QueryImpl.getResultList(QueryImpl.java:492)
	at controllers.RestaurantController.AvgRatingofRestaurant(RestaurantController.java:241)
	at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$31$$anonfun$apply$31.apply(Routes.scala:840)
	at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$31$$anonfun$apply$31.apply(Routes.scala:840)
	at play.core.routing.HandlerInvokerFactory$$anon$4.resultCall(HandlerInvoker.scala:157)
	at play.core.routing.HandlerInvokerFactory$$anon$4.resultCall(HandlerInvoker.scala:156)
	at play.core.routing.HandlerInvokerFactory$JavaActionInvokerFactory$$anon$14$$anon$3$$anon$1.invocation(HandlerInvoker.scala:136)
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:73)
	at play.http.HttpRequestHandler$1.call(HttpRequestHandler.java:54)
	at play.db.jpa.TransactionalAction.lambda$call$4(TransactionalAction.java:28)
	at play.db.jpa.DefaultJPAApi.lambda$withTransaction$3(DefaultJPAApi.java:196)
	at play.db.jpa.DefaultJPAApi.withTransaction(DefaultJPAApi.java:137)
	at play.db.jpa.DefaultJPAApi.withTransaction(DefaultJPAApi.java:195)
	at play.db.jpa.TransactionalAction.call(TransactionalAction.java:25)
	at play.core.j.JavaAction$$anonfun$7.apply(JavaAction.scala:108)
	at play.core.j.JavaAction$$anonfun$7.apply(JavaAction.scala:108)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:56)
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:70)
	at play.core.j.HttpExecutionContext.execute(HttpExecutionContext.scala:48)
	at scala.concurrent.impl.Future$.apply(Future.scala:31)
	at scala.concurrent.Future$.apply(Future.scala:492)
	at play.core.j.JavaAction.apply(JavaAction.scala:108)
	at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5$$anonfun$apply$6.apply(Action.scala:112)
	at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5$$anonfun$apply$6.apply(Action.scala:112)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
	at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5.apply(Action.scala:111)
	at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5.apply(Action.scala:110)
	at scala.Option.map(Option.scala:146)
	at play.api.mvc.Action$$anonfun$apply$2.apply(Action.scala:110)
	at play.api.mvc.Action$$anonfun$apply$2.apply(Action.scala:103)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249)
	... 13 common frames omitted
Caused by: org.hibernate.loader.custom.NonUniqueDiscoveredSqlAliasException: Encountered a duplicated sql alias [Avg_Rating] during auto-discovery of a native-sql query
	at org.hibernate.loader.custom.CustomLoader.validateAliases(CustomLoader.java:513)
	at org.hibernate.loader.custom.CustomLoader.autoDiscoverTypes(CustomLoader.java:490)
	at org.hibernate.loader.Loader.getResultSet(Loader.java:2123)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1898)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1874)
	at org.hibernate.loader.Loader.doQuery(Loader.java:919)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:336)
	at org.hibernate.loader.Loader.doList(Loader.java:2610)
	at org.hibernate.loader.Loader.doList(Loader.java:2593)
	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2422)
	at org.hibernate.loader.Loader.list(Loader.java:2417)
	at org.hibernate.loader.custom.CustomLoader.list(CustomLoader.java:336)
	at org.hibernate.internal.SessionImpl.listCustomQuery(SessionImpl.java:1980)
	at org.hibernate.internal.AbstractSessionImpl.list(AbstractSessionImpl.java:322)
	at org.hibernate.internal.SQLQueryImpl.list(SQLQueryImpl.java:125)
	at org.hibernate.jpa.internal.QueryImpl.list(QueryImpl.java:606)
	at org.hibernate.jpa.internal.QueryImpl.getResultList(QueryImpl.java:483)
	... 46 common frames omitted
2017-03-16 13:16:41,740 [INFO] from application in pool-4-thread-1 - Shutting down connection pool.
